### ISSUE TITLE
Provide the test package as an option

### ISSUE THREAD

**Issue by jinmayamashita** [monstar-lab-oss/ml-frontend#413]
## Overview

Users can select test packages as needed.

## Note

Unit testing seems to be a good idea for now, but there is room for discussion.

## To resolve this issue
- [x] Write unit tests for all modules #710 
- [x] Add to e2e testing packages #720 
- [x] Add storybook config as packages #710
- [x] Enable test options selection in cli
